version: '3.3'
services:
  hadoop-namenode:
    build: ./hadoop
    hostname: hadoop-namenode
    ports: 
      - "2222:2222"
      - "4040:4040"
      - "8020:8020"
      - "8088:8088"
      - "9001:9001"
      - "50070:50070"
      - "50090:50090"
    expose:
      - "8030-8050"
    environment:
      - HDFS_REPLICATION_FACTOR=1
      - HADOOP_NAMENODE_HOST=hadoop-namenode
    volumes:
      - ./data/data-master:/data
      - ./data/slaves-config:/config:ro
      - ./data/deployments:/deployments:ro
    tty: true
  hadoop-datanode:
    build: ./hadoop
    hostname: hadoop-datanode
    ports:
      - "8042:8042"
      - "50075:50075"
    expose:
      - "34000-48000"
      - "50010"
      - "50020"
      - "50040"
    environment:
      - HDFS_REPLICATION_FACTOR=1
      - HADOOP_NAMENODE_HOST=hadoop-namenode
    volumes:
      - ./data/data-slave1:/data
      - ./data/slaves-config:/config:ro
  hive-metastore:
    build: 
      context: ./ 
      dockerfile: ./hive/Dockerfile
    entrypoint: /init-hive.sh
    ports:
      - "9083:9083"
      - "10000:10000"
    links:
      - "postgres:postgres"
      - "hadoop-namenode:hadoop-namenode"
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore